//overview3

$("#btn_ontext").click(function(event){
  $('#pop_up').css('display','block')
  })
$("#xpopup").click(function(event){
    $('#pop_up').css('display','none')
  })
//resource 1
$("#btn_w").click(function(event){
  $("#btnwater_tec").css("fill","#FFFFFF");
  $("#btnwater_text").css("fill","#04151F");
  $("#btnsoil_text").css('fill','#FFFFFF');
  $("#btnsoil_tec").css('fill','none');
  $("#btnsoil_tec").css('stroke','#FFFFFF');
  if($('#pic_soil').css("display") == 'none'){
    $("#pic_water").show();
  }
  else{
    $("#pic_soil").hide();
    $("#pic_water").show();
  }
  })
  $("#btn_s").click(function(event){
    $("#btnsoil_tec").css("fill","#FFFFFF");
    $("#btnsoil_text").css("fill","#04151F");
    $("#btnwater_text").css('fill','#FFFFFF');
    $("#btnwater_tec").css('fill','none');
    $("#btnwater_tec").css('stroke','#FFFFFF');
    if($('#pic_water').css("display") == 'none'){
      $("#pic_soil").show();
    }
    else{
      $("#pic_water").hide();
      $("#pic_soil").show();
    }
    })
//10
$("#btn_languse").click(function(event){
  $("#land_tec").css("fill","#FFFFFF");
  $("#land_text").css("fill","#04151F");
  $("#water_text").css('fill','#FFFFFF');
  $("#water_tec").css('fill','none');
  $("#water_tec").css('stroke','#FFFFFF');
  if($('#water').css("display") == 'none'){
    $("#land").show();
  }
  else{
    $("#water").hide();
    $("#land").show();
  }
  })
  $("#btn_wateruse").click(function(event){
    $("#water_tec").css("fill","#FFFFFF");
    $("#water_text").css("fill","#04151F");
    $("#land_text").css('fill','#FFFFFF');
    $("#land_tec").css('fill','none');
    $("#land_tec").css('stroke','#FFFFFF');
    if($('#land').css("display") == 'none'){
      $("#water").show();
    }
    else{
      $("#land").hide();
      $("#water").show();
    }
    })
//chile water scarcity 11
$("#btn1").click(function(event){
  $("#b1_tec").css("fill","#FFFFFF");
  $("#b1_text").css("fill","#04151F");
  $("#b2_text").css('fill','#FFFFFF');
  $("#b2_tec").css('fill','none');
  $("#b2_tec").css('stroke','#FFFFFF');
  $("#b3_text").css('fill','#FFFFFF');
  $("#b3_tec").css('fill','none');
  $("#b3_tec").css('stroke','#FFFFFF');
  if($('#pic2').css("display") == 'none'&& $('#pic3').css("display") == 'none'){
    $("#pic1").show();
  }
  else{
    $("#pic2").hide();
    $("#pic3").hide();
    $("#pic1").show();
  }
})
$("#btn2").click(function(event){
  $("#b2_tec").css("fill","#FFFFFF");
  $("#b2_text").css("fill","#04151F");
  $("#b1_text").css('fill','#FFFFFF');
  $("#b1_tec").css('fill','none');
  $("#b1_tec").css('stroke','#FFFFFF');
  $("#b3_text").css('fill','#FFFFFF');
  $("#b3_tec").css('fill','none');
  $("#b3_tec").css('stroke','#FFFFFF');
  if($('#pic1').css("display") == 'none'&& $('#pic3').css("display") == 'none'){
    $("#pic2").show();
  }
  else{
    $("#pic1").hide();
    $("#pic3").hide();
    $("#pic2").show();
  }
})
$("#btn3").click(function(event){
  $("#b3_tec").css("fill","#FFFFFF");
  $("#b3_text").css("fill","#04151F");
  $("#b2_text").css('fill','#FFFFFF');
  $("#b2_tec").css('fill','none');
  $("#b2_tec").css('stroke','#FFFFFF');
  $("#b1_text").css('fill','#FFFFFF');
  $("#b1_tec").css('fill','none');
  $("#b1_tec").css('stroke','#FFFFFF');
  if($('#pic2').css("display") == 'none'&& $('#pic1').css("display") == 'none'){
    $("#pic3").show();
  }
  else{
    $("#pic2").hide();
    $("#pic1").hide();
    $("#pic3").show();
  }
})
//12
$("#btn_grey").click(function(event){
  $("#grey_tec").css("fill","#FFFFFF");
  $("#grey_text").css("fill","#04151F");
  $("#all_text").css('fill','#FFFFFF');
  $("#all_tec").css('fill','none');
  $("#all_tec").css('stroke','#FFFFFF');
  $("#green_text").css('fill','#FFFFFF');
  $("#green_tec").css('fill','none');
  $("#green_tec").css('stroke','#FFFFFF');
  $("#blue_text").css('fill','#FFFFFF');
  $("#blue_tec").css('fill','none');
  $("#blue_tec").css('stroke','#FFFFFF');
  if($('#all').css("display") == 'none'&& $('#green').css("display") == 'none'&& $('#blue').css("display") == 'none'){
    $("#grey").show();
  }
  else{
    $("#all").hide();
    $("#green").hide();
    $("#blue").hide();
    $("#grey").show();
  }
})

$("#btn_all").click(function(event){
  $("#all_tec").css("fill","#FFFFFF");
  $("#all_text").css("fill","#04151F");
  $("#grey_text").css('fill','#FFFFFF');
  $("#grey_tec").css('fill','none');
  $("#grey_tec").css('stroke','#FFFFFF');
  $("#green_text").css('fill','#FFFFFF');
  $("#green_tec").css('fill','none');
  $("#green_tec").css('stroke','#FFFFFF');
  $("#blue_text").css('fill','#FFFFFF');
  $("#blue_tec").css('fill','none');
  $("#blue_tec").css('stroke','#FFFFFF');
  if($('#grey').css("display") == 'none'&& $('#green').css("display") == 'none'&& $('#blue').css("display") == 'none'){
    $("#all").show();
  }
  else{
    $("#all").show();
    $("#green").hide();
    $("#blue").hide();
    $("#grey").hide();
  }
})

$("#btn_green").click(function(event){
  $("#green_tec").css("fill","#FFFFFF");
  $("#green_text").css("fill","#04151F");
  $("#all_text").css('fill','#FFFFFF');
  $("#all_tec").css('fill','none');
  $("#all_tec").css('stroke','#FFFFFF');
  $("#grey_text").css('fill','#FFFFFF');
  $("#grey_tec").css('fill','none');
  $("#grey_tec").css('stroke','#FFFFFF');
  $("#blue_text").css('fill','#FFFFFF');
  $("#blue_tec").css('fill','none');
  $("#blue_tec").css('stroke','#FFFFFF');
  if($('#all').css("display") == 'none'&& $('#grey').css("display") == 'none'&& $('#blue').css("display") == 'none'){
    $("#green").show();
  }
  else{
    $("#all").hide();
    $("#green").show();
    $("#blue").hide();
    $("#grey").hide();
  }
})

$("#btn_blue").click(function(event){
  $("#blue_tec").css("fill","#FFFFFF");
  $("#blue_text").css("fill","#04151F");
  $("#all_text").css('fill','#FFFFFF');
  $("#all_tec").css('fill','none');
  $("#all_tec").css('stroke','#FFFFFF');
  $("#grey_text").css('fill','#FFFFFF');
  $("#grey_tec").css('fill','none');
  $("#grey_tec").css('stroke','#FFFFFF');
  $("#green_text").css('fill','#FFFFFF');
  $("#green_tec").css('fill','none');
  $("#green_tec").css('stroke','#FFFFFF');
  if($('#all').css("display") == 'none'&& $('#grey').css("display") == 'none'&& $('#green').css("display") == 'none'){
    $("#blue").show();
  }
  else{
    $("#all").hide();
    $("#green").hide();
    $("#blue").show();
    $("#grey").hide();
  }
})

//production growth1

$('.btn_pg1').mouseenter(function(event){
  $('.btn_pg1').addClass('faded');
  $(this).removeClass('faded');
})

$('.btn_pg1').mouseleave(function(event){
  $('.btn_pg1').removeClass('faded');
})
